/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import javax.swing.ImageIcon;

/**
 *
 * @author Tnam1
 */
public class MainAdminNew extends javax.swing.JFrame {

    /**
     * Creates new form MainAdminNew
     */
    public static String nameLogin;
    private Date today = new Date();
    Locale local = new Locale("vi", "VI");
    DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    String date = d.format(today);
    public MainAdminNew() {
        initComponents();
         setUser();
//        today = new Date();
//        local = new Locale("en", "EN");
//        d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
//        date = d.format(today);

        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
                lblTime.setText(" " + gio + " : " + phut + " : " + giay);
            }
        });
        dongho.start();
    }
    
    private void setUser() {
        nameLogin = DangNhap.NameLogin;
        lblUser.setText(nameLogin);

        lblDate.setText(date);
    }
    public void Doimatkhau()
    {
        frmQuanlydoimatkhau frm = new frmQuanlydoimatkhau();
        jTContent.removeAll();
        jTContent.add("Đổi mật khẩu", frm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnQuanlykhoa = new javax.swing.JButton();
        btnQuanllyLop = new javax.swing.JButton();
        btnQuanlyphonghoc = new javax.swing.JButton();
        btnQuanlymon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnQuanlygiangvien = new javax.swing.JButton();
        btnQuanlysinhvien = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnQuanlyGiangDay = new javax.swing.JButton();
        btnQuanlyxetduyet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTContent = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMThongtincanhan = new javax.swing.JMenuItem();
        jMDoimatkhau = new javax.swing.JMenuItem();
        DangXuat = new javax.swing.JMenuItem();
        jMThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuQuanLyKhoa = new javax.swing.JMenuItem();
        jMenuQuanLyLop = new javax.swing.JMenuItem();
        jMenuQuanlyPhongHoc = new javax.swing.JMenuItem();
        jMenuQuanLyMonHoc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemQuanLyGV = new javax.swing.JMenuItem();
        jMenuItemQuanLySV = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemQuanLyLichGiangDay = new javax.swing.JMenuItem();
        jMenuItemXetduyetdangky = new javax.swing.JMenuItem();
        jMenuItemThemKhoaHoc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Tài Khoản:");

        lblUser.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 0, 0));
        lblUser.setText("Admin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Ngày:");

        lblDate.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblDate.setText("22/08/2020");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Giờ:");

        lblTime.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblTime.setText("18:30 PM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblTime))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(255, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MENU");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnQuanlykhoa.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanlykhoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlykhoa.setForeground(new java.awt.Color(204, 0, 51));
        btnQuanlykhoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        btnQuanlykhoa.setText("Quản Lý Khoa");
        btnQuanlykhoa.setAutoscrolls(true);
        btnQuanlykhoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnQuanlykhoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlykhoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlykhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlykhoaActionPerformed(evt);
            }
        });

        btnQuanllyLop.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanllyLop.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanllyLop.setForeground(new java.awt.Color(204, 0, 51));
        btnQuanllyLop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        btnQuanllyLop.setText("Quản Lý Lớp");
        btnQuanllyLop.setAutoscrolls(true);
        btnQuanllyLop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnQuanllyLop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanllyLop.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanllyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanllyLopActionPerformed(evt);
            }
        });

        btnQuanlyphonghoc.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanlyphonghoc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlyphonghoc.setForeground(new java.awt.Color(204, 0, 51));
        btnQuanlyphonghoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        btnQuanlyphonghoc.setText("QL Phòng Học");
        btnQuanlyphonghoc.setAutoscrolls(true);
        btnQuanlyphonghoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnQuanlyphonghoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlyphonghoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlyphonghoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyphonghocActionPerformed(evt);
            }
        });

        btnQuanlymon.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanlymon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlymon.setForeground(new java.awt.Color(204, 0, 51));
        btnQuanlymon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        btnQuanlymon.setText("QL Môn Học");
        btnQuanlymon.setAutoscrolls(true);
        btnQuanlymon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnQuanlymon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlymon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlymon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlymonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 51, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnQuanlygiangvien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlygiangvien.setForeground(new java.awt.Color(204, 0, 204));
        btnQuanlygiangvien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_student_male_32px.png")); // NOI18N
        btnQuanlygiangvien.setText("QL Giảng Viên");
        btnQuanlygiangvien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 2, true));
        btnQuanlygiangvien.setHideActionText(true);
        btnQuanlygiangvien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlygiangvien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlygiangvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlygiangvienActionPerformed(evt);
            }
        });

        btnQuanlysinhvien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlysinhvien.setForeground(new java.awt.Color(204, 0, 204));
        btnQuanlysinhvien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_students_32px.png")); // NOI18N
        btnQuanlysinhvien.setText("QL Sinh Viên");
        btnQuanlysinhvien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 2, true));
        btnQuanlysinhvien.setHideActionText(true);
        btnQuanlysinhvien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlysinhvien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlysinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlysinhvienActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 255, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        btnQuanlyGiangDay.setBackground(new java.awt.Color(204, 204, 255));
        btnQuanlyGiangDay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlyGiangDay.setForeground(new java.awt.Color(51, 102, 0));
        btnQuanlyGiangDay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_news_32px.png")); // NOI18N
        btnQuanlyGiangDay.setText("QL Giảng Dạy");
        btnQuanlyGiangDay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        btnQuanlyGiangDay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlyGiangDay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlyGiangDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyGiangDayActionPerformed(evt);
            }
        });

        btnQuanlyxetduyet.setBackground(new java.awt.Color(204, 204, 255));
        btnQuanlyxetduyet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuanlyxetduyet.setForeground(new java.awt.Color(51, 102, 0));
        btnQuanlyxetduyet.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_natural_user_interface_2_32px.png")); // NOI18N
        btnQuanlyxetduyet.setText("QL Xét duyệt");
        btnQuanlyxetduyet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        btnQuanlyxetduyet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanlyxetduyet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanlyxetduyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyxetduyetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanlyxetduyet, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnQuanlymon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuanlyphonghoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(btnQuanllyLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuanlykhoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnQuanlygiangvien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanlysinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanlyGiangDay, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlykhoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanllyLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlyphonghoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlymon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlygiangvien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlysinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlyGiangDay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanlyxetduyet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QUẢN LÝ ĐĂNG KÝ HỌC PHẦN");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setForeground(new java.awt.Color(51, 0, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 5));
        jPanel4.setPreferredSize(new java.awt.Dimension(543, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Môn: Lập Trình JAVA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Thầy: Ths. Võ Tấn Dũng");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Sinh Viên Thực Hiện:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 204));
        jLabel11.setText("Trần Tiến Nam");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 255));
        jLabel12.setText("Đặng Nguyễn Thiên Phúc");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 255));
        jLabel13.setText("Đoàn Quang Thắng");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 255));
        jLabel14.setText("Nguyễn Hải Thiên");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 255));
        jLabel15.setText("Vũ Thành Nam");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(199, 199, 199)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(207, 207, 207))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(14, 14, 14))
        );

        jTContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTContent.addTab("Main", jPanel7);

        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(64, 33));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(64, 33));

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_account_32px.png")); // NOI18N
        jMenu1.setText("Tài khoản");

        jMThongtincanhan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMThongtincanhan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_registration_32px.png")); // NOI18N
        jMThongtincanhan.setText("Thông Tin Cá Nhân");
        jMThongtincanhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMThongtincanhanActionPerformed(evt);
            }
        });
        jMenu1.add(jMThongtincanhan);

        jMDoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMDoimatkhau.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_password_32px.png")); // NOI18N
        jMDoimatkhau.setText("Đổi mật khẩu");
        jMDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDoimatkhauActionPerformed(evt);
            }
        });
        jMenu1.add(jMDoimatkhau);

        DangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        DangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_home_32px_1.png")); // NOI18N
        DangXuat.setText("Đăng Xuất");
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(DangXuat);

        jMThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMThoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_shutdown_32px_1.png")); // NOI18N
        jMThoat.setText("Thoát");
        jMThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMThoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_news_32px.png")); // NOI18N
        jMenu2.setText("Quản lý chung");

        jMenuQuanLyKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuanLyKhoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        jMenuQuanLyKhoa.setText("Quản Lý Khoa");
        jMenuQuanLyKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanLyKhoaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQuanLyKhoa);

        jMenuQuanLyLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuanLyLop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        jMenuQuanLyLop.setText("Quản Lý Lớp");
        jMenuQuanLyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanLyLopActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQuanLyLop);

        jMenuQuanlyPhongHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuanlyPhongHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        jMenuQuanlyPhongHoc.setText("Quản Lý Phòng Học");
        jMenuQuanlyPhongHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanlyPhongHocActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQuanlyPhongHoc);

        jMenuQuanLyMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuanLyMonHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_folder_32px.png")); // NOI18N
        jMenuQuanLyMonHoc.setText("Quản Lý Môn Học");
        jMenuQuanLyMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanLyMonHocActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQuanLyMonHoc);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_user_male_32px.png")); // NOI18N
        jMenu3.setText("Quản lý người dùng");

        jMenuItemQuanLyGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemQuanLyGV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_student_male_32px.png")); // NOI18N
        jMenuItemQuanLyGV.setText("Quản Lý Giảng Viên");
        jMenuItemQuanLyGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuanLyGVActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemQuanLyGV);

        jMenuItemQuanLySV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemQuanLySV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_students_32px.png")); // NOI18N
        jMenuItemQuanLySV.setText("Quản Lý Sinh Viên");
        jMenuItemQuanLySV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuanLySVActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemQuanLySV);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_calendar_32px_1.png")); // NOI18N
        jMenu4.setText("Quản Lý Khóa Học");

        jMenuItemQuanLyLichGiangDay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemQuanLyLichGiangDay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_hotel_check_out_32px.png")); // NOI18N
        jMenuItemQuanLyLichGiangDay.setText("Quản Lý Lịch Giảng Dạy");
        jMenuItemQuanLyLichGiangDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuanLyLichGiangDayActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemQuanLyLichGiangDay);

        jMenuItemXetduyetdangky.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemXetduyetdangky.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_hotel_check_out_32px.png")); // NOI18N
        jMenuItemXetduyetdangky.setText("Xét duyệt đăng ký");
        jMenuItemXetduyetdangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemXetduyetdangkyActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemXetduyetdangky);

        jMenuItemThemKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemThemKhoaHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\JAVA\\DAMHJava\\src\\Icon\\icons8_database_32px.png")); // NOI18N
        jMenuItemThemKhoaHoc.setText("Thêm Khóa Học");
        jMenuItemThemKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThemKhoaHocActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemThemKhoaHoc);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTContent))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTContent)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanllyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanllyLopActionPerformed
        // TODO add your handling code here:
        frmQuanLyLop frm = new frmQuanLyLop();
        jTContent.removeAll();
        jTContent.add("Quản Lý Lớp", frm);
    }//GEN-LAST:event_btnQuanllyLopActionPerformed

    private void btnQuanlysinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlysinhvienActionPerformed
        // TODO add your handling code here:
        frmQuanLySinhVien frm = new frmQuanLySinhVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Sinh Viên", frm);
    }//GEN-LAST:event_btnQuanlysinhvienActionPerformed

    private void btnQuanlyGiangDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyGiangDayActionPerformed
        // TODO add your handling code here:
        frmQuanLyLopGiangDay frm = new frmQuanLyLopGiangDay();
        jTContent.removeAll();
        jTContent.add("Quản Lý Giảng Dạy", frm);
    }//GEN-LAST:event_btnQuanlyGiangDayActionPerformed

    private void btnQuanlykhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlykhoaActionPerformed
        // TODO add your handling code here:
        frmQuanLyKhoa frm = new frmQuanLyKhoa();
        jTContent.removeAll();
        jTContent.add("Quản Lý Khoa", frm);
    }//GEN-LAST:event_btnQuanlykhoaActionPerformed

    private void jMThongtincanhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMThongtincanhanActionPerformed
        // TODO add your handling code here:
        frmQuanlyThongtincanhan frm = new frmQuanlyThongtincanhan();
        jTContent.removeAll();
        jTContent.add("Thông tin cá nhân", frm);
        
    }//GEN-LAST:event_jMThongtincanhanActionPerformed

    private void jMenuQuanlyPhongHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanlyPhongHocActionPerformed
        // TODO add your handling code here:
        frmQuanLyPhongHoc frm = new frmQuanLyPhongHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Phòng Học", frm);
    }//GEN-LAST:event_jMenuQuanlyPhongHocActionPerformed

    private void jMenuItemQuanLySVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuanLySVActionPerformed
        // TODO add your handling code here:
        frmQuanLySinhVien frm = new frmQuanLySinhVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Sinh Viên", frm);
    }//GEN-LAST:event_jMenuItemQuanLySVActionPerformed

    private void jMDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDoimatkhauActionPerformed
        // TODO add your handling code here:
        frmQuanlydoimatkhau frm = new frmQuanlydoimatkhau();
        jTContent.removeAll();
        jTContent.add("Đổi Mật Khẩu", frm);
    }//GEN-LAST:event_jMDoimatkhauActionPerformed

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        dispose();
    }//GEN-LAST:event_DangXuatActionPerformed

    private void jMThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMThoatActionPerformed

    private void jMenuQuanLyKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanLyKhoaActionPerformed
        // TODO add your handling code here:
        frmQuanLyKhoa frm = new frmQuanLyKhoa();
        jTContent.removeAll();
        jTContent.add("Quản Lý Khoa", frm);

    }//GEN-LAST:event_jMenuQuanLyKhoaActionPerformed

    private void jMenuQuanLyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanLyLopActionPerformed
        // TODO add your handling code here:
        frmQuanLyLop frm = new frmQuanLyLop();
        jTContent.removeAll();
        jTContent.add("Quản Lý Lớp", frm);
    }//GEN-LAST:event_jMenuQuanLyLopActionPerformed

    private void jMenuQuanLyMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanLyMonHocActionPerformed
        // TODO add your handling code here:
        frmQuanLyMonHoc frm = new frmQuanLyMonHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Môn Học", frm);
    }//GEN-LAST:event_jMenuQuanLyMonHocActionPerformed

    private void jMenuItemQuanLyGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuanLyGVActionPerformed
        // TODO add your handling code here:
         frmQuanLyGiaoVien frm = new frmQuanLyGiaoVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Giảng Viên", frm);
    }//GEN-LAST:event_jMenuItemQuanLyGVActionPerformed

    private void jMenuItemQuanLyLichGiangDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuanLyLichGiangDayActionPerformed
        // TODO add your handling code here:
        frmQuanLyLopGiangDay frm = new frmQuanLyLopGiangDay();
        jTContent.removeAll();
        jTContent.add("Quản Lý Lịch Giảng Dạy", frm);
    }//GEN-LAST:event_jMenuItemQuanLyLichGiangDayActionPerformed

    private void jMenuItemXetduyetdangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemXetduyetdangkyActionPerformed
        // TODO add your handling code here:
        frmQuanLyXetDuyetMoLop frm = new frmQuanLyXetDuyetMoLop();
        jTContent.removeAll();
        jTContent.add("Xét Duyệt Môn Đăng Ký", frm);
    }//GEN-LAST:event_jMenuItemXetduyetdangkyActionPerformed

    private void btnQuanlyphonghocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyphonghocActionPerformed
        // TODO add your handling code here:
        frmQuanLyPhongHoc frm = new frmQuanLyPhongHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Phòng Học", frm);
    }//GEN-LAST:event_btnQuanlyphonghocActionPerformed

    private void btnQuanlymonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlymonActionPerformed
        // TODO add your handling code here:
        frmQuanLyMonHoc frm = new frmQuanLyMonHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Môn Học", frm);
    }//GEN-LAST:event_btnQuanlymonActionPerformed

    private void btnQuanlygiangvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlygiangvienActionPerformed
        // TODO add your handling code here:
        frmQuanLyGiaoVien frm = new frmQuanLyGiaoVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Giảng Viên", frm);
    }//GEN-LAST:event_btnQuanlygiangvienActionPerformed

    private void btnQuanlyxetduyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyxetduyetActionPerformed
        // TODO add your handling code here:
        frmQuanLyXetDuyetMoLop frm = new frmQuanLyXetDuyetMoLop();
        jTContent.removeAll();
        jTContent.add("Xét Duyệt Mở Lớp", frm);
    }//GEN-LAST:event_btnQuanlyxetduyetActionPerformed

    private void jMenuItemThemKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThemKhoaHocActionPerformed
        // TODO add your handling code here:
         frmThemHocPhan frm = new frmThemHocPhan();
        jTContent.removeAll();
        jTContent.add("Thêm Học Phần", frm);
    }//GEN-LAST:event_jMenuItemThemKhoaHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdminNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdminNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdminNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdminNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdminNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DangXuat;
    private javax.swing.JButton btnQuanllyLop;
    private javax.swing.JButton btnQuanlyGiangDay;
    private javax.swing.JButton btnQuanlygiangvien;
    private javax.swing.JButton btnQuanlykhoa;
    private javax.swing.JButton btnQuanlymon;
    private javax.swing.JButton btnQuanlyphonghoc;
    private javax.swing.JButton btnQuanlysinhvien;
    private javax.swing.JButton btnQuanlyxetduyet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMDoimatkhau;
    private javax.swing.JMenuItem jMThoat;
    private javax.swing.JMenuItem jMThongtincanhan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemQuanLyGV;
    private javax.swing.JMenuItem jMenuItemQuanLyLichGiangDay;
    private javax.swing.JMenuItem jMenuItemQuanLySV;
    private javax.swing.JMenuItem jMenuItemThemKhoaHoc;
    private javax.swing.JMenuItem jMenuItemXetduyetdangky;
    private javax.swing.JMenuItem jMenuQuanLyKhoa;
    private javax.swing.JMenuItem jMenuQuanLyLop;
    private javax.swing.JMenuItem jMenuQuanLyMonHoc;
    private javax.swing.JMenuItem jMenuQuanlyPhongHoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTContent;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
