/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import java.awt.BorderLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.Timer;

/**
 *
 * @author Tnam1
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        Date date =new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        String strDate = formatter.format(date);
        jLDay.setText(strDate);
//        SimpleDateFormat formatterTime = new SimpleDateFormat("HH:mm a");
//        String strTime =formatterTime.format(date);
//        jLTime.setText(strTime);
        jLName.setText(DangNhap.NameLogin);
        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
                int buoi = lich.get(Calendar.AM_PM);
                jLTime.setText(" " + gio + " : " + phut + " : " + giay+ "   "+buoi);
            }
        });
        dongho.start();
        TrangChu frm= new TrangChu();
        jTContent.removeAll();
        jTContent.add("Trang Chủ", frm);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLDay = new javax.swing.JLabel();
        jLTime = new javax.swing.JLabel();
        jTContent = new javax.swing.JTabbedPane();
        jPContainer = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        JMTaiKhoan = new javax.swing.JMenu();
        ItemThongTin = new javax.swing.JMenuItem();
        ItemMK = new javax.swing.JMenuItem();
        ItemDangXuat = new javax.swing.JMenuItem();
        JMQuanly = new javax.swing.JMenu();
        jMQuanLyLop = new javax.swing.JMenuItem();
        jMQuanLyMon = new javax.swing.JMenuItem();
        jMQuanLyPhongHoc = new javax.swing.JMenuItem();
        jMQuanLyKhoa = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMGiangVien = new javax.swing.JMenuItem();
        jMHocSinh = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMXetduyetmolop = new javax.swing.JMenu();
        jMLopgiangday = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1060, 658));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jLName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLName.setForeground(new java.awt.Color(255, 51, 51));
        jLName.setText("Admin");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Xin chào:");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày :");

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giờ:");

        jLDay.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLDay.setForeground(new java.awt.Color(255, 255, 255));
        jLDay.setText("20/06/2020");

        jLTime.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLTime.setForeground(new java.awt.Color(255, 255, 255));
        jLTime.setText("18:30 PM");
        jLTime.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLTimeInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLDay, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLName))
                .addContainerGap())
        );

        jTContent.setMinimumSize(new java.awt.Dimension(1106, 638));
        jTContent.setPreferredSize(new java.awt.Dimension(1106, 638));

        javax.swing.GroupLayout jPContainerLayout = new javax.swing.GroupLayout(jPContainer);
        jPContainer.setLayout(jPContainerLayout);
        jPContainerLayout.setHorizontalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
        );
        jPContainerLayout.setVerticalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        jTContent.addTab("Giao diện", jPContainer);

        Menu.setBackground(new java.awt.Color(204, 204, 255));

        JMTaiKhoan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_user_male_32px.png")); // NOI18N
        JMTaiKhoan.setText("Tài Khoản");

        ItemThongTin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        ItemThongTin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_user_folder_32px.png")); // NOI18N
        ItemThongTin.setText("Thông Tin");
        ItemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemThongTinActionPerformed(evt);
            }
        });
        JMTaiKhoan.add(ItemThongTin);

        ItemMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        ItemMK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_password_32px.png")); // NOI18N
        ItemMK.setText("Đổi Mật Khẩu");
        ItemMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMKActionPerformed(evt);
            }
        });
        JMTaiKhoan.add(ItemMK);

        ItemDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        ItemDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_shutdown_32px_1.png")); // NOI18N
        ItemDangXuat.setText("Đăng Xuất");
        ItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDangXuatActionPerformed(evt);
            }
        });
        JMTaiKhoan.add(ItemDangXuat);

        Menu.add(JMTaiKhoan);

        JMQuanly.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_database_32px.png")); // NOI18N
        JMQuanly.setText("Quản Lý");

        jMQuanLyLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMQuanLyLop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_natural_user_interface_2_32px.png")); // NOI18N
        jMQuanLyLop.setText("Quản Lý Lớp");
        jMQuanLyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMQuanLyLopActionPerformed(evt);
            }
        });
        JMQuanly.add(jMQuanLyLop);

        jMQuanLyMon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMQuanLyMon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_ringer_volume_32px.png")); // NOI18N
        jMQuanLyMon.setText("Quản Lý Môn");
        jMQuanLyMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMQuanLyMonActionPerformed(evt);
            }
        });
        JMQuanly.add(jMQuanLyMon);

        jMQuanLyPhongHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMQuanLyPhongHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_news_32px.png")); // NOI18N
        jMQuanLyPhongHoc.setText("Quản Lý Phòng Học");
        jMQuanLyPhongHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMQuanLyPhongHocActionPerformed(evt);
            }
        });
        JMQuanly.add(jMQuanLyPhongHoc);

        jMQuanLyKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMQuanLyKhoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_search_32px_1.png")); // NOI18N
        jMQuanLyKhoa.setText("Quản Lý Khoa");
        jMQuanLyKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMQuanLyKhoaActionPerformed(evt);
            }
        });
        JMQuanly.add(jMQuanLyKhoa);

        Menu.add(JMQuanly);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_user_account_32px.png")); // NOI18N
        jMenu1.setText("Nhóm Người Dùng");

        jMGiangVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMGiangVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_student_male_32px.png")); // NOI18N
        jMGiangVien.setText("Giảng Viên");
        jMGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGiangVienActionPerformed(evt);
            }
        });
        jMenu1.add(jMGiangVien);

        jMHocSinh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMHocSinh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_students_32px.png")); // NOI18N
        jMHocSinh.setText("Học Sinh");
        jMHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMHocSinhActionPerformed(evt);
            }
        });
        jMenu1.add(jMHocSinh);

        Menu.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_search_32px_1.png")); // NOI18N
        jMenu2.setText("Tìm Kiếm");
        Menu.add(jMenu2);

        jMXetduyetmolop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_hotel_check_out_32px.png")); // NOI18N
        jMXetduyetmolop.setText("Xét Duyệt Mở Lớp");
        jMXetduyetmolop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMXetduyetmolopMouseClicked(evt);
            }
        });
        Menu.add(jMXetduyetmolop);

        jMLopgiangday.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tnam1\\OneDrive\\Desktop\\IconJava\\icons8_combo_chart_32px.png")); // NOI18N
        jMLopgiangday.setText("Lớp Giảng Dạy");
        jMLopgiangday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMLopgiangdayMouseClicked(evt);
            }
        });
        Menu.add(jMLopgiangday);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTContent.getAccessibleContext().setAccessibleName("Giao diện");
        jTContent.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDangXuatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemDangXuatActionPerformed

    private void jLTimeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLTimeInputMethodTextChanged
        // TODO Date date =new Date();
        Date date =new Date();
        SimpleDateFormat formatterTime = new SimpleDateFormat("HH:mm a");
        String strTime =formatterTime.format(date);
        if(evt.equals(strTime)== false)
        {
            jLTime.setText(strTime);
        }
    }//GEN-LAST:event_jLTimeInputMethodTextChanged

    private void jMQuanLyMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMQuanLyMonActionPerformed
        // TODO add your handling code here:
        frmQuanLyMonHoc frm= new frmQuanLyMonHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Môn", frm);
    }//GEN-LAST:event_jMQuanLyMonActionPerformed

    private void jMQuanLyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMQuanLyLopActionPerformed
        // TODO add your handling code here:
        frmQuanLyLop frm= new frmQuanLyLop();
        jTContent.removeAll();
        jTContent.add("Quản Lý Lớp", frm);
//        jPContainer.removeAll();
//        jPContainer.setLayout( new BorderLayout());
//        jPContainer.add(frm);     
//        jPContainer.validate();
//        jPContainer.repaint();
    }//GEN-LAST:event_jMQuanLyLopActionPerformed

    private void jMQuanLyPhongHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMQuanLyPhongHocActionPerformed
        // TODO add your handling code here:
        frmQuanLyPhongHoc frm= new frmQuanLyPhongHoc();
        jTContent.removeAll();
        jTContent.add("Quản Lý Phòng Học", frm);
//        jPContainer.removeAll();
//        jPContainer.setLayout( new BorderLayout());
//        jPContainer.add(frm);     
//        jPContainer.validate();
//        jPContainer.repaint();
    }//GEN-LAST:event_jMQuanLyPhongHocActionPerformed

    private void jMQuanLyKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMQuanLyKhoaActionPerformed
        // TODO add your handling code here:
         frmQuanLyKhoa frm= new frmQuanLyKhoa();
        jTContent.removeAll();
        jTContent.add("Quản Lý Khoa", frm);
//        frmQuanLyKhoa frm= new frmQuanLyKhoa();
//        jPContainer.removeAll();
//        jPContainer.setLayout( new BorderLayout());
//        jPContainer.add(frm);     
//        jPContainer.validate();
//        jPContainer.repaint();
    }//GEN-LAST:event_jMQuanLyKhoaActionPerformed

    private void jMGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGiangVienActionPerformed
        // TODO add your handling code here:
        frmQuanLyGiaoVien frm= new frmQuanLyGiaoVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Giảng Viên", frm);
//        jPContainer.removeAll();
//        jPContainer.setLayout( new BorderLayout());
//        jPContainer.add(frm);     
//        jPContainer.validate();
//        jPContainer.repaint();
    }//GEN-LAST:event_jMGiangVienActionPerformed

    private void jMHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMHocSinhActionPerformed
        // TODO add your handling code here:
        frmQuanLySinhVien frm= new frmQuanLySinhVien();
        jTContent.removeAll();
        jTContent.add("Quản Lý Học Sinh", frm);
//        jPContainer.removeAll();
//        jPContainer.setLayout( new BorderLayout());
//        jPContainer.add(frm);     
//        jPContainer.validate();
//        jPContainer.repaint();
    }//GEN-LAST:event_jMHocSinhActionPerformed

    private void jMXetduyetmolopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMXetduyetmolopMouseClicked
        // TODO add your handling code here:
        frmQuanLyXetDuyetMoLop frm= new frmQuanLyXetDuyetMoLop();
        jTContent.removeAll();
        jTContent.add("Xét duyệt mở lớp", frm);
    }//GEN-LAST:event_jMXetduyetmolopMouseClicked

    private void jMLopgiangdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMLopgiangdayMouseClicked
        // TODO add your handling code here:
        frmQuanLyLopGiangDay frm= new frmQuanLyLopGiangDay();
        jTContent.removeAll();
        jTContent.add("Lớp giảng dạy", frm);
    }//GEN-LAST:event_jMLopgiangdayMouseClicked

    private void ItemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemThongTinActionPerformed
        // TODO add your handling code here:
        frmQuanlyThongtincanhan frm= new frmQuanlyThongtincanhan();
        jTContent.removeAll();
        jTContent.add("Thông Tin Cá Nhân", frm);
    }//GEN-LAST:event_ItemThongTinActionPerformed

    private void ItemMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMKActionPerformed
        // TODO add your handling code here:
        frmQuanlydoimatkhau frm= new frmQuanlydoimatkhau();
        jTContent.removeAll();
        jTContent.add("Đổi mật khẩu", frm);
    }//GEN-LAST:event_ItemMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDangXuat;
    private javax.swing.JMenuItem ItemMK;
    private javax.swing.JMenuItem ItemThongTin;
    private javax.swing.JMenu JMQuanly;
    private javax.swing.JMenu JMTaiKhoan;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLDay;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLTime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMGiangVien;
    private javax.swing.JMenuItem jMHocSinh;
    private javax.swing.JMenu jMLopgiangday;
    private javax.swing.JMenuItem jMQuanLyKhoa;
    private javax.swing.JMenuItem jMQuanLyLop;
    private javax.swing.JMenuItem jMQuanLyMon;
    private javax.swing.JMenuItem jMQuanLyPhongHoc;
    private javax.swing.JMenu jMXetduyetmolop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTContent;
    // End of variables declaration//GEN-END:variables
}
